// Code generated by ogen, DO NOT EDIT.
package senzingchatapi

type EntityDetailsEntityDetailsGetRes interface {
	entityDetailsEntityDetailsGetRes()
}

type EntityHowEntityHowGetRes interface {
	entityHowEntityHowGetRes()
}

type EntityReportEntityReportGetRes interface {
	entityReportEntityReportGetRes()
}

type EntitySearchEntitySearchPostRes interface {
	entitySearchEntitySearchPostRes()
}
